version: "3.9"

services:
  # Broker Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"   # Porta MQTT padr√£o
      - "9001:9001"   # WebSocket (opcional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - iot_network

  # API FastAPI
  api_gateway:
    build: .
    container_name: gateway_api
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER_HOST=mosquitto
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge
